"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WEEK 5 — POSTERIOR PREDICTIVE CHECKS & CONVERGENCE DIAGNOSTICS
─────────────────────────────────────────────────────────────────
Validates the four Bayesian fits sampled in Week 4 (Gaussian, Laplace
= symmetric VG, Student-t, NIG).  Week 4 produced clean posteriors
(R-hat 1.000, ESS > 2,000, no divergences); Week 5 asks the two
questions that decide whether those fits are trustworthy:

  1. POSTERIOR PREDICTIVE CHECK — does each model, when you simulate
     replicate return series from its posterior, reproduce the
     features of the observed 6,287 S&P 500 log-returns that the
     project actually cares about?  The thesis lives in the TAILS, so
     the PPC statistics are tail-weighted: VaR/ES at 95%, 97.5% (the
     FRTB ES level) and 99%, excess kurtosis, min/max, each reported
     with a posterior-predictive credible band and a Bayesian p-value.
     One DEPENDENCE statistic is included on purpose: the lag-1
     autocorrelation of squared returns (volatility clustering, Cont
     2001).  All four models are iid, so all four are expected to fail
     it.  That failure shows where a static marginal stops working and
     is the reason for the Week 6 rolling backtest.
     Expectation: the Gaussian PPC should visibly FAIL in the tails
     (the Bayesian echo of the 79.5% ES gap) while Student-t and NIG
     cover the extremes.

  2. CONVERGENCE DIAGNOSTICS — fuller than the Week 4 eyeball: R-hat,
     bulk-ESS AND tail-ESS (tail-ESS matters because the ES/VaR
     numbers are tail quantiles), MCSE, and divergence counts.

INPUTS  (no re-sampling — reuses Week 4 output)
───────
  week4/data/sp500_returns.csv            observed returns (6,287 obs)
  week4/data/week4_posterior_<model>.csv  posterior draws per model

Because the posteriors are stored as plain parameter draws, the PPC
here is generated by sampling the likelihood at each posterior draw
(ancestral / posterior-predictive simulation in numpy/scipy) rather
than via pm.sample_posterior_predictive — no PyMC model rebuild and
no NetCDF backend needed.  This mirrors the Week 4 decision to persist
draws as CSV.

OUTPUTS
───────
  week5/figures/week5_ppc_<model>.png        density + tail overlay
  week5/figures/week5_ppc_risk.png           VaR/ES bands vs empirical
  week5/figures/week5_diagnostics_<model>.png
  week5/data/week5_ppc_stats.csv             test stats + Bayesian p
  week5/data/week5_diagnostics.csv           R-hat / ESS / MCSE table

Run standalone:
    python week5_ppc.py                 # all four models
    python week5_ppc.py --model nig
    python week5_ppc.py --reps 2000     # posterior-predictive replicates
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

import os
import sys
import argparse
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats as sps

warnings.filterwarnings("ignore")
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

_HERE = os.path.dirname(os.path.abspath(__file__))
_W4_DATA = os.path.abspath(os.path.join(_HERE, "..", "..", "week4", "data"))

ALL_MODELS = ["gaussian", "laplace", "student_t", "nig"]

DISPLAY = {
    "gaussian":  "Gaussian",
    "laplace":   "Laplace",
    "student_t": "Student-t",
    "nig":       "NIG",
}

# Match the Week 3 / levy_models palette so figures stay consistent.
MODEL_COLOURS = {
    "gaussian":  "steelblue",
    "laplace":   "purple",
    "student_t": "crimson",
    "nig":       "darkorange",
}

ALPHAS = (0.95, 0.975, 0.99)   # 97.5% is the FRTB/Basel III ES confidence level


def _alpha_label(a):
    """0.95 -> '95', 0.975 -> '97.5', 0.99 -> '99'."""
    return f"{a * 100:g}"


# ── data / posterior loading ──────────────────────────────────────────────────

def load_returns(path=os.path.join(_W4_DATA, "sp500_returns.csv")):
    s = pd.read_csv(path, index_col=0, parse_dates=True).iloc[:, 0]
    s.name = "logret"
    print(f"Loaded {len(s)} observed returns from {path}")
    return s.values.astype(float)


def load_posterior(name, data_dir=_W4_DATA):
    path = os.path.join(data_dir, f"week4_posterior_{name}.csv")
    df = pd.read_csv(path)
    print(f"Loaded posterior for {name}: {len(df)} draws from {path}")
    return df


# ── posterior-predictive simulation ───────────────────────────────────────────
#
# For each of `reps` posterior draws we generate a replicate dataset the same
# size as the observed sample (n), drawing from that draw's likelihood.  This is
# the standard posterior-predictive construction: integrate the data model over
# the posterior.

def _simulate_one(name, row, n, rng):
    """One replicate dataset of length n from a single posterior draw `row`."""
    if name == "gaussian":
        return rng.normal(row["mu"], row["sigma"], size=n)
    if name == "laplace":
        return rng.laplace(row["mu"], row["b"], size=n)
    if name == "student_t":
        # location-scale Student-t: mu + sigma * t_nu
        return row["mu"] + row["sigma"] * rng.standard_t(row["nu"], size=n)
    if name == "nig":
        # scipy parametrisation: a = alpha*delta, b = beta*delta, scale = delta
        return sps.norminvgauss.rvs(a=row["alpha"] * row["delta"],
                                    b=row["beta"] * row["delta"],
                                    loc=row["mu"], scale=row["delta"],
                                    size=n, random_state=rng)
    raise ValueError(f"unknown model: {name}")


def _acf1_sq(x):
    """Lag-1 autocorrelation of squared returns: the volatility clustering
    statistic (Cont 2001).  All four fitted models are iid, so their
    replicates have ACF ≈ 0 by construction; the observed series does not.
    Included so the PPC also tests a DEPENDENCE feature rather than
    marginal ones only."""
    s = x**2
    s = s - s.mean()
    return float(np.sum(s[1:] * s[:-1]) / np.sum(s * s))


def _stats_vector(x):
    """Test statistics computed on a return vector (observed or replicate)."""
    out = {
        "std":          float(np.std(x)),
        "excess_kurt":  float(sps.kurtosis(x, fisher=True)),
        "skew":         float(sps.skew(x)),
        "min":          float(np.min(x)),
        "max":          float(np.max(x)),
        "acf_sq_1":     _acf1_sq(x),
    }
    for a in ALPHAS:
        var = float(np.quantile(x, 1.0 - a))
        es  = float(x[x <= var].mean())
        out[f"VaR_{_alpha_label(a)}"] = var
        out[f"ES_{_alpha_label(a)}"]  = es
    return out


def posterior_predictive(name, post, n, reps, seed=42):
    """
    Returns
    -------
    rep_stats : pd.DataFrame  (reps rows, one column per test statistic)
    reps_raw  : np.ndarray    (reps, n) replicate returns, for density plots
    """
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, len(post), size=reps)
    rows = post.iloc[idx].reset_index(drop=True)

    recs = []
    reps_raw = np.empty((reps, n), dtype=float)
    for i in range(reps):
        sim = _simulate_one(name, rows.iloc[i], n, rng)
        reps_raw[i] = sim
        recs.append(_stats_vector(sim))
    return pd.DataFrame(recs), reps_raw


def bayesian_pvalue(rep_vals, obs_val):
    """
    Two-sided posterior-predictive p-value: tail probability that a replicate
    statistic is at least as extreme as the observed one.  Values near 0 or 1
    flag a feature the model fails to reproduce; near 0.5 is a good fit.
    """
    p_right = float(np.mean(rep_vals >= obs_val))
    return 2.0 * min(p_right, 1.0 - p_right)


# ── figures ───────────────────────────────────────────────────────────────────

def plot_ppc_density(name, obs, reps_raw, save_dir):
    """Observed return histogram with a fan of posterior-predictive densities,
    plus a left-tail zoom (where the models diverge)."""
    colour = MODEL_COLOURS[name]
    fig, (ax, axz) = plt.subplots(1, 2, figsize=(12, 4.5))

    grid = np.linspace(-0.12, 0.12, 400)
    # density fan: KDE per replicate is slow, so use a shared histogram envelope
    n_show = min(60, reps_raw.shape[0])
    for j in range(n_show):
        h, edges = np.histogram(reps_raw[j], bins=grid, density=True)
        centres = 0.5 * (edges[:-1] + edges[1:])
        ax.plot(centres, h, color=colour, alpha=0.06, lw=0.8)
    ho, edges = np.histogram(obs, bins=grid, density=True)
    centres = 0.5 * (edges[:-1] + edges[1:])
    ax.plot(centres, ho, color="k", lw=1.6, label="Observed")
    ax.plot([], [], color=colour, alpha=0.6, label=f"Posterior predictive")
    ax.set_title(f"Posterior predictive density — {DISPLAY[name]}")
    ax.set_xlabel("Daily log-return")
    ax.set_ylabel("Density")
    ax.legend(fontsize=9)

    # left-tail zoom on log scale
    tgrid = np.linspace(-0.15, -0.03, 200)
    for j in range(n_show):
        h, edges = np.histogram(reps_raw[j], bins=tgrid, density=True)
        c = 0.5 * (edges[:-1] + edges[1:])
        axz.plot(c, h, color=colour, alpha=0.06, lw=0.8)
    ho, edges = np.histogram(obs, bins=tgrid, density=True)
    c = 0.5 * (edges[:-1] + edges[1:])
    axz.plot(c, ho, color="k", lw=1.6, label="Observed")
    axz.set_yscale("log")
    axz.set_title("Left-tail zoom (log density)")
    axz.set_xlabel("Daily log-return")
    axz.set_ylabel("Density (log)")

    fig.tight_layout()
    out = os.path.join(save_dir, f"week5_ppc_{name}.png")
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  saved -> {out}")


def plot_risk_bands(rep_stats_by_model, obs_stats, save_dir):
    """Posterior-predictive VaR/ES credible intervals vs the empirical values."""
    metrics = [f"{m}_{_alpha_label(a)}" for a in ALPHAS for m in ("VaR", "ES")]
    labels  = [f"{m} {_alpha_label(a)}%" for a in ALPHAS for m in ("VaR", "ES")]
    models = list(rep_stats_by_model)

    fig, axes = plt.subplots(1, len(metrics), figsize=(4 * len(metrics), 4.5),
                             sharey=False)
    for ax, metric, label in zip(axes, metrics, labels):
        for k, name in enumerate(models):
            vals = rep_stats_by_model[name][metric].values
            lo, mid, hi = np.quantile(vals, [0.03, 0.5, 0.97])
            ax.errorbar(k, mid, yerr=[[mid - lo], [hi - mid]], fmt="o",
                        color=MODEL_COLOURS[name], capsize=4, lw=1.5,
                        label=DISPLAY[name] if metric == metrics[0] else None)
        ax.axhline(obs_stats[metric], color="k", ls="--", lw=1.2)
        ax.set_xticks(range(len(models)))
        ax.set_xticklabels([DISPLAY[m] for m in models], rotation=30, fontsize=8)
        ax.set_title(label)
        ax.yaxis.set_major_formatter(lambda v, _: f"{v:.1%}")
    axes[0].set_ylabel("Return")
    fig.suptitle("Posterior-predictive tail risk (94% band) vs empirical "
                 "(dashed)", y=1.02)
    fig.legend(loc="lower center", ncol=len(models), fontsize=9,
               bbox_to_anchor=(0.5, -0.08))
    fig.tight_layout()
    out = os.path.join(save_dir, "week5_ppc_risk.png")
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  saved -> {out}")


# ── convergence diagnostics ────────────────────────────────────────────────────
#
# Computed directly from the (chain, draw) layout in the posterior CSVs, so the
# diagnostics need neither arviz nor a re-sample.  In the spirit of
# Vehtari et al. (2021): split-R-hat (without their rank-normalisation step),
# bulk-ESS via Geyer's initial-monotone-sequence estimator, and tail-ESS as
# the ESS of the 5%/95% quantile indicators.  For these well-mixed, unimodal
# posteriors the rank-normalisation refinement makes no practical difference;
# the Week 4 az.summary output gives a library cross-check.

def _split_chains(x):
    """x: (n_chain, n_draw) -> (2*n_chain, n_draw//2) split-half chains."""
    n_chain, n_draw = x.shape
    h = n_draw // 2
    return np.concatenate([x[:, :h], x[:, h:2 * h]], axis=0)


def _rhat(x):
    """Split-R-hat on (n_chain, n_draw)."""
    s = _split_chains(x)
    m, n = s.shape
    chain_means = s.mean(axis=1)
    chain_vars = s.var(axis=1, ddof=1)
    W = chain_vars.mean()
    B = n * chain_means.var(ddof=1)
    var_hat = (n - 1) / n * W + B / n
    return float(np.sqrt(var_hat / W)) if W > 0 else np.nan


def _ess(x):
    """Bulk ESS via the autocorrelation of split chains (Geyer initial
    monotone sequence estimator)."""
    s = _split_chains(x)
    m, n = s.shape
    # autocovariance averaged across chains via FFT
    acov = np.zeros(n)
    for c in range(m):
        y = s[c] - s[c].mean()
        f = np.fft.rfft(y, n=2 * n)
        ac = np.fft.irfft(f * np.conjugate(f))[:n]
        acov += ac
    acov /= m
    if acov[0] == 0:
        return float(m * n)
    rho = acov / acov[0]
    # Geyer: sum paired autocorrelations while positive
    t = 1
    rho_sum = 0.0
    while t + 1 < n:
        pair = rho[t] + rho[t + 1]
        if pair < 0:
            break
        rho_sum += pair
        t += 2
    tau = 1.0 + 2.0 * rho_sum
    return float(m * n / tau) if tau > 0 else float(m * n)


def _ess_tail(x):
    """Tail ESS: min of the ESS of the 5% and 95% indicator series."""
    def ind_ess(q):
        thr = np.quantile(x, q)
        ind = (x <= thr).astype(float)
        return _ess(ind)
    return float(min(ind_ess(0.05), ind_ess(0.95)))


def diagnostics(name, post):
    param_cols = [c for c in post.columns if c not in ("chain", "draw")]
    n_chain = post["chain"].nunique()
    recs = []
    for p in param_cols:
        wide = (post.pivot(index="chain", columns="draw", values=p)
                    .sort_index().values)            # (n_chain, n_draw)
        mean = float(wide.mean())
        sd = float(wide.std(ddof=1))
        ess_bulk = _ess(wide)
        ess_tail = _ess_tail(wide)
        mcse = sd / np.sqrt(ess_bulk) if ess_bulk > 0 else np.nan
        recs.append({
            "model": name, "param": p, "mean": mean, "sd": sd,
            "r_hat": _rhat(wide), "ess_bulk": ess_bulk,
            "ess_tail": ess_tail, "mcse": mcse,
        })
    df = pd.DataFrame(recs)
    print(f"\n── Diagnostics: {name} ──")
    print(df.to_string(index=False,
                       float_format=lambda v: f"{v:.4g}"))
    return df


def plot_diagnostics(name, post, save_dir):
    """Per-parameter trace + running mean as a convergence eyeball."""
    param_cols = [c for c in post.columns if c not in ("chain", "draw")]
    n = len(param_cols)
    fig, axes = plt.subplots(n, 1, figsize=(9, 2.2 * n), squeeze=False)
    for i, p in enumerate(param_cols):
        ax = axes[i, 0]
        for c, sub in post.groupby("chain"):
            ax.plot(sub["draw"].values, sub[p].values, lw=0.4, alpha=0.6)
        ax.set_ylabel(p)
    axes[0, 0].set_title(f"Traces by chain — {DISPLAY[name]}")
    axes[-1, 0].set_xlabel("Draw")
    fig.tight_layout()
    out = os.path.join(save_dir, f"week5_diagnostics_{name}.png")
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"  saved -> {out}")


# ── orchestration ──────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description="Week 5 PPC + convergence diagnostics")
    ap.add_argument("--model", choices=ALL_MODELS + ["all"], default="all")
    ap.add_argument("--reps", type=int, default=1000,
                    help="number of posterior-predictive replicate datasets")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--fig_dir", default=os.path.join(_HERE, "..", "figures"))
    ap.add_argument("--data_dir", default=os.path.join(_HERE, "..", "data"))
    args = ap.parse_args()

    fig_dir = os.path.abspath(args.fig_dir)
    data_dir = os.path.abspath(args.data_dir)
    os.makedirs(fig_dir, exist_ok=True)
    os.makedirs(data_dir, exist_ok=True)

    obs = load_returns()
    n = len(obs)
    obs_stats = _stats_vector(obs)

    models = ALL_MODELS if args.model == "all" else [args.model]

    ppc_rows = []
    rep_stats_by_model = {}
    diag_frames = []

    for name in models:
        print("\n" + "=" * 64)
        print(f"MODEL: {name}")
        print("=" * 64)
        post = load_posterior(name)

        # 1. posterior predictive
        rep_stats, reps_raw = posterior_predictive(name, post, n, args.reps,
                                                   seed=args.seed)
        rep_stats_by_model[name] = rep_stats
        plot_ppc_density(name, obs, reps_raw, fig_dir)

        print(f"\n── Posterior predictive statistics: {name} ──")
        print(f"  {'stat':<12}{'observed':>12}{'pp median':>12}"
              f"{'94% band':>22}{'Bayes p':>10}")
        for stat in rep_stats.columns:
            vals = rep_stats[stat].values
            lo, mid, hi = np.quantile(vals, [0.03, 0.5, 0.97])
            p = bayesian_pvalue(vals, obs_stats[stat])
            flag = "  <- fails" if (p < 0.05 or p > 0.95) else ""
            print(f"  {stat:<12}{obs_stats[stat]:>12.4f}{mid:>12.4f}"
                  f"   [{lo:>8.4f},{hi:>8.4f}]{p:>10.3f}{flag}")
            ppc_rows.append({
                "model": name, "stat": stat, "observed": obs_stats[stat],
                "pp_median": mid, "pp_lo": lo, "pp_hi": hi, "bayes_p": p,
            })

        # 2. convergence diagnostics
        diag_frames.append(diagnostics(name, post))
        plot_diagnostics(name, post, fig_dir)

    # combined figures / tables
    if len(rep_stats_by_model) > 1:
        plot_risk_bands(rep_stats_by_model, obs_stats, fig_dir)

    ppc_path = os.path.join(data_dir, "week5_ppc_stats.csv")
    pd.DataFrame(ppc_rows).to_csv(ppc_path, index=False)
    print(f"\nPPC stats -> {ppc_path}")

    diag_path = os.path.join(data_dir, "week5_diagnostics.csv")
    pd.concat(diag_frames, ignore_index=True).to_csv(diag_path, index=False)
    print(f"Diagnostics -> {diag_path}")


if __name__ == "__main__":
    main()
